# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pedrosacosta.github.io
title: Dr. Eng. Pedro Costa | Senior Researcher
author: Pedro Costa
email: pedrosacosta.pt@gmail.com
description: "Pedro Costa (or Pedro A.R.S. Costa, or Pedro Sá da Costa) is a Senior Researcher at IoT Innovation Lab at Lucerne University of Applied Sciences and Arts, Lucerne, Switzerland. Before coming to Switzerland, he has work in industry and academia for 16+ YoE."
copyright: 'Copyright &copy; 2021 Pedro Sa da Costa. All Rights Reserved.'
credits: 'Theme: <a href="https://github.com/swcool/landing-page-theme">landing-page-theme</a>.'
lang: en-US

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
social:
  # - title: GitHub
  #   icon: fa-github
  #   url: https://github.com/xeon123
  - title: CV
    icon: fa-file-pdf-o
    url: https://www.dropbox.com/s/po3pj7g0x1hls6l/CURRICULUM_VITAE-Pedro_Costa-public-version.pdf?dl=0
    # original Google Docs document: https://docs.google.com/document/d/14WhT62GUSVQTd5wCfzUHfXZa-bJRmPDH4vnxX2E5dBQ
  - title: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/pedrosacosta
  - title: ORCID
    icon: fab fa-orcid
    url: https://orcid.org/0000-0003-0780-8216
  - title: Scholar
    icon: fa-google
    url: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Pedro+Costa&btnG=
  - title: Blog
    icon: fab fa-blogger
    url: https://computersciencetalks.blogspot.com

google_analytics: G-CCEMLPTW4V
